services:
  mongo:
    image: mongo:latest
    container_name: allocineMongoDB
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

  app:
    build: .
    image: projetdataengineeringnathan-app
    container_name: projetdataengineeringnathan-app
    command: python main.py
    depends_on:
      - mongo
    ports:
      - "8050:8050"
    restart: on-failure

volumes:
  mongo-data:
